// Self-hosted sample files (public/samples), described by sample-manifest.json.
// Both are generated by scripts/prepare-samples.mjs.

import * as Tone from 'tone';
import manifest from './sample-manifest.json';

const BASE = `${import.meta.env.BASE_URL}samples/`;

export type PitchedSet = keyof typeof manifest.pitched;
export type DrumPiece = keyof typeof manifest.drums;
export const DRUM_PIECES = Object.keys(manifest.drums) as DrumPiece[];

/** Pitched samples: buffers[noteIndex][layer][roundRobin], notes as MIDI numbers. */
export interface SampleSet {
  notes: number[];
  buffers: AudioBuffer[][][];
  /** Extra one-shots, e.g. muted string scratches. */
  noises: AudioBuffer[];
  /** String-damping noises for when notes are stopped. */
  releases: AudioBuffer[];
}

const LOAD_TIMEOUT = 20000;

function withTimeout<T>(p: Promise<T>, what: string): Promise<T> {
  return Promise.race([
    p,
    new Promise<T>((_, reject) => setTimeout(() => reject(new Error(`Timed out loading ${what}`)), LOAD_TIMEOUT)),
  ]);
}

/**
 * One sample file, retried a few times: web hosts (GitHub Pages) sometimes answer a burst of
 * requests with a passing error, and one missing file would otherwise drop a whole instrument
 * to its synth stand-in for the session.
 */
async function load(path: string): Promise<AudioBuffer> {
  for (let attempt = 0; ; attempt++) {
    try {
      return await Tone.ToneAudioBuffer.load(`${BASE}${path}`);
    } catch (e) {
      if (attempt >= 3) throw e;
      await new Promise((r) => setTimeout(r, 300 * 2 ** attempt));
    }
  }
}
const range = (n: number) => Array.from({ length: n }, (_, i) => i + 1);

/** Decoded sets are shared, so two parts on the same instrument don't load (or use memory) twice. */
const pitchedCache = new Map<PitchedSet, Promise<SampleSet>>();

export function loadPitched(set: PitchedSet): Promise<SampleSet> {
  let p = pitchedCache.get(set);
  if (!p) {
    p = loadPitchedUncached(set);
    pitchedCache.set(set, p);
    p.catch(() => pitchedCache.delete(set)); // allow a retry after a failure
  }
  return p;
}

async function loadPitchedUncached(set: PitchedSet): Promise<SampleSet> {
  const m = manifest.pitched[set];
  return withTimeout((async () => ({
    notes: m.notes,
    buffers: await Promise.all(m.notes.map((midi) =>
      Promise.all(range(m.layers).map((l) => Promise.all(range(m.rr).map((r) => load(`${set}/${midi}-${l}-${r}.mp3`))))))),
    noises: await Promise.all(range(m.noises).map((i) => load(`${set}/mute-${i}.mp3`))),
    releases: await Promise.all(range(m.releases).map((i) => load(`${set}/rel-${i}.mp3`))),
  }))(), set);
}

let drumCache: Promise<Record<DrumPiece, AudioBuffer[][]>> | null = null;

/** Drum buffers: [layer][roundRobin] per piece (loaded once, shared). */
export function loadDrums(): Promise<Record<DrumPiece, AudioBuffer[][]>> {
  if (!drumCache) {
    drumCache = loadDrumsUncached();
    drumCache.catch(() => { drumCache = null; });
  }
  return drumCache;
}

async function loadDrumsUncached(): Promise<Record<DrumPiece, AudioBuffer[][]>> {
  const entries = await withTimeout(
    Promise.all(DRUM_PIECES.map(async (piece) => {
      const { layers, rr } = manifest.drums[piece];
      const bufs = await Promise.all(range(layers).map((l) =>
        Promise.all(range(rr).map((r) => load(`drums/${piece}-${l}-${r}.mp3`)))));
      return [piece, bufs] as const;
    })),
    'drums',
  );
  return Object.fromEntries(entries) as Record<DrumPiece, AudioBuffer[][]>;
}

/** Pick a round robin, avoiding the one used last time for the same slot. */
export class RoundRobin {
  private last = new Map<string, number>();

  pick<T>(key: string, items: T[]): T {
    if (items.length === 1) return items[0];
    const prev = this.last.get(key) ?? -1;
    let i = Math.floor(Math.random() * (items.length - 1));
    if (i >= prev) i++;
    this.last.set(key, i);
    return items[i];
  }
}

export type CabName = 'clean' | 'crunch' | 'dist';

const cabCache = new Map<CabName, Promise<AudioBuffer>>();

/** Speaker cabinet impulse response for the electric guitar amp (loaded once, shared). */
export function loadCab(name: CabName): Promise<AudioBuffer> {
  let p = cabCache.get(name);
  if (!p) {
    p = withTimeout(load(`ir/${name}.wav`), `${name} cabinet`);
    cabCache.set(name, p);
    p.catch(() => cabCache.delete(name));
  }
  return p;
}
